# Site settings
title: My Personal Blog
description: A collection of posts about stuff I read and learned
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sygn.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Željko Tadić
user_description: Hi
user_title: Software Engineer
email: zeljko.tadic.91@gmail.com
twitter_username: ztadic91
github_username:  sygn
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
